MODEL:
  NAME: 'resnet50' # 'resnet50' 'seresnet50' 'densenet169'
  PRETRAIN_PATH: '/kaggle/input/nd-twin-256/resnet50-19c8e357.pth' # pretrained resnest50 model; change it to your path
  # PRETRAIN_PATH_SE: '/home/cgy/.torch/models/seresnet50-60a8950a85b2b.pkl'
  # PRETRAIN_PATH_DENSE: '/home/cgy/.torch/models/densenet169-b2777c0a.pth'
  CAL: True


INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.0
  PADDING: 0

DATASETS:
  NAMES: ('list_reid') # custom list-based dataset for training
  IMAGE_ROOT: '/kaggle/input/nd-twin-256/ND_TWIN_256'
  TRAIN_LIST: '/kaggle/input/nd-twin-256/train_reid.txt'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 1000
  BASE_LR: 0.0002
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.001
  WEIGHT_DECAY_BIAS: 0.001
  SMOOTH: 0.1
  IMS_PER_BATCH: 80

  STEPS: [40, 80, 120]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 20
  EVAL_PERIOD: 10


TEST:
  IMS_PER_BATCH: 128
  RE_RANK: False
  WEIGHT: "path"
  PAIRS_FILE: '/kaggle/input/nd-twin-256/test_pairs.txt'  # set to pairs file path to enable verification eval

OUTPUT_DIR: "checkpoint/ndtwin"
